# Project Name - Brazilian E-Commerce by Olist

## 🗂️ **Data Processing Pipeline Summary**  

This script performs the following steps to prepare the dataset:

1. Importing Datasets : Loads all CSV files required for the analysis.

2. Dataset Exploration : Reviews and summarizes each CSV file to understand the structure,columns, and overall data content.

3. Data Cleaning Handles missing (null) values , Fixes inconsistent or incorrect data types, Removes or corrects invalid entries where necessary.

4. Data Integration Merges all cleaned datasets into a single consolidated dataframe.

5. Exporting Final Dataset Saves the final cleaned and merged dataset into a CSV file for further analysis or use in downstream processes.

# **📥 Setup & Configuration**

In [2]:
# 📘 1. IMPORT LIBRARIES
import pandas as pd
import numpy as np

# 📂 2. LOAD DATA
customers = pd.read_csv('olist_customers_dataset.csv')
orders = pd.read_csv('olist_orders_dataset.csv')
order_items = pd.read_csv('olist_order_items_dataset.csv')
products = pd.read_csv('olist_products_dataset.csv')
payments = pd.read_csv('olist_order_payments_dataset.csv')
reviews = pd.read_csv('olist_order_reviews_dataset.csv')
sellers = pd.read_csv('olist_sellers_dataset.csv')
geolocation = pd.read_csv('olist_geolocation_dataset.csv')
category_translation = pd.read_csv('product_category_name_translation.csv')

# **🔍 Data Profiling / Initial Inspection**

In [3]:
# 🔍 2.1 QUICK SHAPE OVERVIEW
print(f"customers     shape: {customers.shape}      #olist_customers_dataset.csv")
print(f"orders        shape: {orders.shape}         # olist_orders_dataset.csv")
print(f"order_items   shape: {order_items.shape}    # olist_order_items_dataset")
print(f"products      shape: {products.shape}       # olist_products_dataset")
print(f"payments      shape: {payments.shape}       # olist_order_payments_dataset")
print(f"reviews       shape: {reviews.shape}        # olist_order_reviews_dataset")
print(f"sellers       shape: {sellers.shape}        # olist_sellers_dataset")
print(f"geolocation   shape: {geolocation.shape}    # olist_geolocation_dataset")
print(f"category_translation shape: {category_translation.shape}        # product_category_name_translation")

customers     shape: (99441, 5)      #olist_customers_dataset.csv
orders        shape: (99441, 8)         # olist_orders_dataset.csv
order_items   shape: (112650, 7)    # olist_order_items_dataset
products      shape: (32951, 9)       # olist_products_dataset
payments      shape: (103886, 5)       # olist_order_payments_dataset
reviews       shape: (99224, 7)        # olist_order_reviews_dataset
sellers       shape: (3095, 4)        # olist_sellers_dataset
geolocation   shape: (1000163, 5)    # olist_geolocation_dataset
category_translation shape: (71, 2)        # product_category_name_translation

In [4]:
# 🔍 2.x — QUICK VIEW OF ALL RAW DATAFRAMES
# -----------------------------------------
# Print first few rows for each sheet

print("\n— customers head —")
display(customers.head())
print()

print("\n— orders head —")
display(orders.head())
print()

print("\n— order_items head —")
display(order_items.head())
print()

print("\n— products head —")
display(products.head())
print()

print("\n— payments head —")
display(payments.head())
print()

print("\n— reviews head —")
display(reviews.head())

print("\n— sellers head —")
display(sellers.head())
print()

print("\n— geolocation head —")
display(geolocation.head())
print()

print("\n— category_translation head —")
display(category_translation.head())

— customers head —

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

— orders head —

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

— order_items head —

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

— products head —

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

— payments head —

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

— reviews head —

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

— sellers head —

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

— geolocation head —

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

— category_translation head —

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

# *🧹 Data Cleaning & Wrangling*

In [5]:
# ====================== BASIC CLEANING FUNCTION ======================
def clean_table(df, name):
    print(f"\n{'='*60}")
    print(f"Cleaning: {name}")
    print(f"Original Shape: {df.shape}")
    
    # 1. Drop exact duplicate rows (if any)
    df = df.drop_duplicates()
    
    # 2. Strip whitespace from all string columns
    for col in df.select_dtypes(include='object').columns:
        df[col] = df[col].str.strip()
    
    print(f"Shape after cleaning: {df.shape}")
    return df

In [6]:
# Apply basic cleaning
customers = clean_table(customers, "Customers")
orders = clean_table(orders, "Orders")
order_items = clean_table(order_items, "Order Items")
products = clean_table(products, "Products")
payments = clean_table(payments, "Payments")
reviews = clean_table(reviews, "Reviews")

============================================================
Cleaning: Customers
Original Shape: (99441, 5)
Shape after cleaning: (99441, 5)

============================================================
Cleaning: Orders
Original Shape: (99441, 8)
Shape after cleaning: (99441, 8)

============================================================
Cleaning: Order Items
Original Shape: (112650, 7)
Shape after cleaning: (112650, 7)

============================================================
Cleaning: Products
Original Shape: (32951, 9)
Shape after cleaning: (32951, 9)

============================================================
Cleaning: Payments
Original Shape: (103886, 5)
Shape after cleaning: (103886, 5)

============================================================
Cleaning: Reviews
Original Shape: (99224, 7)
Shape after cleaning: (99224, 7)

In [7]:
# ====================== SPECIFIC CLEANING ======================

# 1. Customers Table

customers['customer_city'] = customers['customer_city'].str.lower()
customers['customer_state'] = customers['customer_state'].str.upper()
print('Customer Table Done ')

# 2. Orders Table 

orders['order_status'] = orders['order_status'].str.lower()

date_columns = ['order_purchase_timestamp', 'order_approved_at', 
                'order_delivered_carrier_date', 'order_delivered_customer_date', 
                'order_estimated_delivery_date']

for col in date_columns:
    if col in orders.columns:
        orders[col]=pd.to_datetime(orders[col], errors='coerce')
# Creating new columns
orders['delivery_days'] = (orders['order_delivered_customer_date']-orders['order_purchase_timestamp']).dt.days
orders['is_late'] = orders['order_delivered_customer_date'] > orders['order_estimated_delivery_date']


# 3. Order Items
order_items['total_value'] = order_items['price'] + order_items['freight_value']


# 4. Products Table 

products['product_category_name'] = products['product_category_name'].str.lower()

if category_translation is not None:
    products = products.merge(category_translation, 
                              on='product_category_name', 
                              how='left')

# 5. Payments
payments['payment_type'] = payments['payment_type'].str.title()

# 6. Reviews
reviews['has_review'] = reviews['review_score'].notna().astype(int)

# ====================== FINAL SUMMARY ======================
print("\n" + "="*80)
print("DATA CLEANING COMPLETED!")
print("="*80)
print(f"Customers Shape     : {customers.shape}")
print(f"Orders Shape        : {orders.shape}")
print(f"Order Items Shape   : {order_items.shape}")
print(f"Products Shape      : {products.shape}")
print(f"Payments Shape      : {payments.shape}")
print(f"Reviews Shape       : {reviews.shape}")

# Check remaining missing values in key columns
print("\nMissing Values in Orders (Key Columns):")
print(orders[['order_delivered_customer_date', 'delivery_days']].isnull().sum())

Customer Table Done

================================================================================
DATA CLEANING COMPLETED!
================================================================================
Customers Shape     : (99441, 5)
Orders Shape        : (99441, 10)
Order Items Shape   : (112650, 8)
Products Shape      : (32951, 10)
Payments Shape      : (103886, 5)
Reviews Shape       : (99224, 8)

Missing Values in Orders (Key Columns):
order_delivered_customer_date    2965
delivery_days                    2965
dtype: int64

#  🔄 Dataset Merging & Saving As CSV File

In [11]:
# ====================== MERGING TABLES ======================

# Orders + Customers
master = orders.merge(customers , on = 'customer_id', how = 'left' )

# Order Items 
master = master.merge(order_items, on='order_id', how ='left')

# Products 
master = master.merge(products[['product_id', 'product_category_name', 'product_category_name_english']], 
                      on='product_id', how='left')

#Payments
master = master.merge(payments, on='order_id', how='left')

# Reviews
master = master.merge(reviews[['order_id', 'review_score', 'has_review']], 
                      on='order_id', how='left')

print("✅ Master table created successfully!")
print(f"Final Master Shape: {master.shape}")


# ====================== SUMMARY OF MASTER TABLE ======================
print("\n" + "="*80)
print("MASTER TABLE SUMMARY")
print("="*80)
print(master.info())



print("\nMissing Values in Master Table (Top 10 columns with most missing):")
print(master.isnull().sum().sort_values(ascending=False).head(12))


# Saving the master file
master.to_csv('master_sales_data.csv', index=False)
print("\n✅ Master file saved as 'master_sales_data.csv'")

✅ Master table created successfully!
Final Master Shape: (119143, 29)

================================================================================
MASTER TABLE SUMMARY
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 29 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  object
 1   customer_id                    119143 non-null  object
 2   order_status                   119143 non-null  object
 3   order_purchase_timestamp       119143 non-null  datetime64[ns]
 4   order_approved_at              118966 non-null  datetime64[ns]
 5   order_delivered_carrier_date   117057 non-null  datetime64[ns]
 6   order_delivered_customer_date  115722 non-null  datetime64[ns]
 7   order_estimated_delivery_date  119143 non-null  datetime64[ns]
 8   delivery_days                  115722 non-null  float64
 9   is_late                        119143 non-null  bool
 10  customer_unique_id             119143 non-null  object
 11  customer_zip_code_prefix       119143 non-null  int64
 12  customer_city                  119143 non-null  object
 13  customer_state                 119143 non-null  object
 14  order_item_id                  118310 non-null  float64
 15  product_id                     118310 non-null  object
 16  seller_id                      118310 non-null  object
 17  shipping_limit_date            118310 non-null  object
 18  price                          118310 non-null  float64
 19  freight_value                  118310 non-null  float64
 20  total_value                    118310 non-null  float64
 21  product_category_name          116601 non-null  object
 22  product_category_name_english  116576 non-null  object
 23  payment_sequential             119140 non-null  float64
 24  payment_type                   119140 non-null  object
 25  payment_installments           119140 non-null  float64
 26  payment_value                  119140 non-null  float64
 27  review_score                   118146 non-null  float64
 28  has_review                     118146 non-null  float64
dtypes: bool(1), datetime64[ns](5), float64(10), int64(1), object(12)
memory usage: 25.6+ MB
None

Missing Values in Master Table (Top 10 columns with most missing):
order_delivered_customer_date    3421
delivery_days                    3421
product_category_name_english    2567
product_category_name            2542
order_delivered_carrier_date     2086
review_score                      997
has_review                        997
product_id                        833
order_item_id                     833
shipping_limit_date               833
seller_id                         833
total_value                       833
dtype: int64

✅ Master file saved as 'master_sales_data.csv'

# 📊  Data Preview

In [12]:
print("\nFirst 5 rows preview:")
master.head(5)

First 5 rows preview:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,is_late,...,freight_value,total_value,product_category_name,product_category_name_english,payment_sequential,payment_type,payment_installments,payment_value,review_score,has_review
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8.0,False,...,8.72,38.71,utilidades_domesticas,housewares,1.0,Credit_Card,1.0,18.12,4.0,1.0
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8.0,False,...,8.72,38.71,utilidades_domesticas,housewares,3.0,Voucher,1.0,2.00,4.0,1.0
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8.0,False,...,8.72,38.71,utilidades_domesticas,housewares,2.0,Voucher,1.0,18.59,4.0,1.0
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,13.0,False,...,22.76,141.46,perfumaria,perfumery,1.0,Boleto,1.0,141.46,4.0,1.0
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9.0,False,...,19.22,179.12,automotivo,auto,1.0,Credit_Card,3.0,179.12,5.0,1.0